import AppKit
import Observation
import SwiftUI
import AnaclastCore

struct ClipboardEntry: Codable, Identifiable, Hashable, Sendable {
    enum Content: Codable, Hashable, Sendable {
        case text(String)
        case files([URL])
        case image(String)
    }

    let id: UUID
    let content: Content
    let copiedAt: Date
    let sourceBundleID: String?

    var searchText: String {
        switch content {
        case .text(let text): String(text.prefix(2000))
        case .files(let urls): urls.map(\.lastPathComponent).joined(separator: " ")
        case .image: "Image"
        }
    }

    var preview: String {
        switch content {
        case .text(let text):
            let line = text.split(whereSeparator: \.isNewline).first.map(String.init) ?? text
            return line.trimmingCharacters(in: .whitespaces)
        case .files(let urls):
            return urls.map(\.lastPathComponent).joined(separator: ", ")
        case .image:
            return "Image"
        }
    }
}

@MainActor
@Observable
final class ClipboardHistory {
    private(set) var entries: [ClipboardEntry] = []
    @ObservationIgnored var limit: Int?
    @ObservationIgnored private var lastChangeCount = NSPasteboard.general.changeCount
    @ObservationIgnored private var timer: Timer?

    static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "net.antelle.keeweb",
    ]

    static let directory: URL = {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        return base.appending(path: "Anaclast/clipboard", directoryHint: .isDirectory)
    }()

    static var indexURL: URL { directory.appending(path: "history.json") }

    init(limit: Int?) {
        self.limit = limit
        load()
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.ignoredTypes), let content = capture(pasteboard) else { return }
        let source = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        insert(ClipboardEntry(id: UUID(), content: content, copiedAt: .now, sourceBundleID: source))
    }

    private func capture(_ pasteboard: NSPasteboard) -> ClipboardEntry.Content? {
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            return .files(urls)
        }
        if let text = pasteboard.string(forType: .string), !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return .text(text)
        }
        if let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff), let image = NSImage(data: data),
           let tiff = image.tiffRepresentation, let png = NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:]) {
            let name = UUID().uuidString + ".png"
            do {
                try FileManager.default.createDirectory(at: Self.directory, withIntermediateDirectories: true)
                try png.write(to: Self.directory.appending(path: name))
                return .image(name)
            } catch {
                log.error("clipboard image save failed: \(error.localizedDescription, privacy: .public)")
            }
        }
        return nil
    }

    private func insert(_ entry: ClipboardEntry) {
        entries.removeAll { $0.content == entry.content }
        entries.insert(entry, at: 0)
        if let limit, entries.count > limit {
            removeImages(of: Array(entries[limit...]))
            entries = Array(entries.prefix(limit))
        }
        save()
    }

    func remove(_ entry: ClipboardEntry) {
        entries.removeAll { $0.id == entry.id }
        removeImages(of: [entry])
        save()
    }

    func imageURL(_ name: String) -> URL { Self.directory.appending(path: name) }

    func copy(_ entry: ClipboardEntry) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        switch entry.content {
        case .text(let text):
            pasteboard.setString(text, forType: .string)
        case .files(let urls):
            pasteboard.writeObjects(urls.map { $0 as NSURL })
        case .image(let name):
            if let image = NSImage(contentsOf: imageURL(name)) { pasteboard.writeObjects([image]) }
        }
        lastChangeCount = pasteboard.changeCount
        entries.removeAll { $0.id == entry.id }
        entries.insert(ClipboardEntry(id: entry.id, content: entry.content, copiedAt: .now, sourceBundleID: entry.sourceBundleID), at: 0)
        save()
    }

    private func removeImages(of removed: [ClipboardEntry]) {
        for entry in removed {
            guard case .image(let name) = entry.content else { continue }
            do {
                try FileManager.default.removeItem(at: imageURL(name))
            } catch {
                log.error("clipboard image cleanup failed: \(error.localizedDescription, privacy: .public)")
            }
        }
    }

    private func load() {
        guard let data = try? Data(contentsOf: Self.indexURL) else { return }
        do {
            entries = try JSONDecoder().decode([ClipboardEntry].self, from: data)
        } catch {
            log.error("clipboard history unreadable: \(error.localizedDescription, privacy: .public)")
        }
    }

    private func save() {
        do {
            try FileManager.default.createDirectory(at: Self.directory, withIntermediateDirectories: true)
            try JSONEncoder().encode(entries).write(to: Self.indexURL, options: .atomic)
        } catch {
            log.error("clipboard history save failed: \(error.localizedDescription, privacy: .public)")
        }
    }
}

@MainActor
@Observable
final class ClipboardModel {
    var query = ""
    var selection = 0
    private(set) var presentation = 0
    private(set) var results: [ClipboardEntry] = []
    @ObservationIgnored let history: ClipboardHistory
    @ObservationIgnored private let searcher = Searcher()
    @ObservationIgnored var paste: (ClipboardEntry) -> Void = { _ in }
    @ObservationIgnored var dismiss: () -> Void = {}

    init(history: ClipboardHistory) {
        self.history = history
    }

    func refresh() {
        if query.trimmingCharacters(in: .whitespaces).isEmpty {
            results = history.entries
        } else {
            results = searcher.rank(history.entries, query: query, title: \.searchText).map(\.item)
        }
        selection = 0
    }

    var selected: ClipboardEntry? {
        results.indices.contains(selection) ? results[selection] : nil
    }

    func presented() {
        query = ""
        presentation += 1
        refresh()
    }

    func move(_ delta: Int) {
        let count = results.count
        guard count > 0 else { return }
        selection = (selection + delta + count) % count
    }

    func activate() {
        guard let entry = selected else { return }
        paste(entry)
    }

    func deleteSelected() {
        guard let entry = selected else { return }
        let index = selection
        history.remove(entry)
        results.removeAll { $0.id == entry.id }
        selection = min(index, max(results.count - 1, 0))
    }
}

struct ClipboardView: View {
    @Bindable var model: ClipboardModel

    var body: some View {
        VStack(spacing: 0) {
            HStack(spacing: 12) {
                Image(systemName: "list.clipboard")
                    .font(.system(size: 20, weight: .medium))
                    .foregroundStyle(.secondary)
                SearchField(placeholder: "Search clipboard history", text: $model.query, presentation: model.presentation) { command in
                    switch command {
                    case #selector(NSResponder.insertNewline(_:)): model.activate()
                    case #selector(NSResponder.moveUp(_:)): model.move(-1)
                    case #selector(NSResponder.moveDown(_:)): model.move(1)
                    case #selector(NSResponder.cancelOperation(_:)): model.dismiss()
                    case #selector(NSResponder.deleteToBeginningOfLine(_:)): model.deleteSelected()
                    default: return false
                    }
                    return true
                }
            }
            .padding(.horizontal, 20)
            .frame(height: 58)
            Divider()
            HStack(spacing: 0) {
                ClipboardList(model: model)
                    .frame(width: 300)
                Divider()
                ClipboardPreview(entry: model.selected, history: model.history)
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
            }
        }
        .containerShape(.rect(cornerRadius: IslandShape.bottomRadius))
        .onChange(of: model.query) { model.refresh() }
    }
}

private struct ClipboardList: View {
    @Bindable var model: ClipboardModel

    var body: some View {
        let results = model.results
        ScrollViewReader { proxy in
            ScrollView {
                LazyVStack(spacing: 2) {
                    ForEach(Array(results.enumerated()), id: \.element.id) { index, entry in
                        HStack(spacing: 10) {
                            ClipboardGlyph(entry: entry, history: model.history)
                                .frame(width: 20, height: 20)
                            Text(entry.preview)
                                .font(.system(size: 13))
                                .lineLimit(1)
                            Spacer(minLength: 0)
                        }
                        .padding(.horizontal, 10)
                        .frame(height: 34)
                        .background {
                            if index == model.selection {
                                ConcentricRectangle().fill(.primary.opacity(0.1))
                            }
                        }
                        .id(entry.id)
                        .contentShape(.rect)
                        .onTapGesture {
                            model.selection = index
                            model.activate()
                        }
                    }
                }
                .padding(8)
            }
            .scrollIndicators(.never)
            .onChange(of: model.selection) {
                guard let entry = model.selected else { return }
                proxy.scrollTo(entry.id)
            }
        }
    }
}

private struct ClipboardGlyph: View {
    let entry: ClipboardEntry
    let history: ClipboardHistory

    var body: some View {
        switch entry.content {
        case .text:
            Image(systemName: "text.alignleft").foregroundStyle(.secondary)
        case .files(let urls):
            if let first = urls.first {
                Image(nsImage: IconCache.icon(for: first)).resizable().aspectRatio(contentMode: .fit)
            }
        case .image:
            Image(systemName: "photo").foregroundStyle(.secondary)
        }
    }
}

private struct ClipboardPreview: View {
    let entry: ClipboardEntry?
    let history: ClipboardHistory

    var body: some View {
        if let entry {
            VStack(alignment: .leading, spacing: 12) {
                content(entry)
                    .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
                Divider()
                LabeledContent("Copied", value: entry.copiedAt.formatted(.relative(presentation: .named)))
                    .font(.system(size: 12))
                if let source = entry.sourceBundleID, let url = NSWorkspace.shared.urlForApplication(withBundleIdentifier: source) {
                    LabeledContent("Source", value: FileManager.default.displayName(atPath: url.path))
                        .font(.system(size: 12))
                }
            }
            .padding(16)
        } else {
            Text("No clipboard history yet")
                .foregroundStyle(.secondary)
        }
    }

    @ViewBuilder
    private func content(_ entry: ClipboardEntry) -> some View {
        switch entry.content {
        case .text(let text):
            ScrollView {
                Text(String(text.prefix(20_000)))
                    .font(.system(size: 13, design: .monospaced))
                    .textSelection(.enabled)
                    .frame(maxWidth: .infinity, alignment: .leading)
            }
        case .files(let urls):
            VStack(alignment: .leading, spacing: 6) {
                ForEach(urls, id: \.self) { url in
                    Label {
                        Text(url.path).font(.system(size: 12)).lineLimit(2)
                    } icon: {
                        Image(nsImage: IconCache.icon(for: url)).resizable().frame(width: 18, height: 18)
                    }
                }
            }
        case .image(let name):
            if let image = NSImage(contentsOf: history.imageURL(name)) {
                Image(nsImage: image).resizable().aspectRatio(contentMode: .fit)
            }
        }
    }
}
